<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="7" total="24" passed="17">
  <reporter-output>
      <![CDATA[Method name is e2]]>
  </reporter-output>
  <suite name="main-suite" duration-ms="98" started-at="2015-03-10T06:23:10Z" finished-at="2015-03-10T06:23:10Z">
    <groups>
      <group name="myGroup">
        <method signature="TestClass1.t1()[pri:0, instance:com.javacodegeeks.testng.reports.TestClass1@31b7dea0]" name="t1" class="com.javacodegeeks.testng.reports.TestClass1"/>
        <method signature="TestClass1.t2()[pri:0, instance:com.javacodegeeks.testng.reports.TestClass1@31b7dea0]" name="t2" class="com.javacodegeeks.testng.reports.TestClass1"/>
        <method signature="TestClass1.t3()[pri:0, instance:com.javacodegeeks.testng.reports.TestClass1@31b7dea0]" name="t3" class="com.javacodegeeks.testng.reports.TestClass1"/>
      </group> <!-- myGroup -->
    </groups>
    <test name="main-suite-test1" duration-ms="98" started-at="2015-03-10T06:23:10Z" finished-at="2015-03-10T06:23:10Z">
      <class name="com.javacodegeeks.testng.reports.TestClass1">
        <test-method status="FAIL" signature="t1()[pri:0, instance:com.javacodegeeks.testng.reports.TestClass1@31b7dea0]" name="t1" duration-ms="0" started-at="2015-03-10T11:53:10Z" finished-at="2015-03-10T11:53:10Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at com.javacodegeeks.testng.reports.TestClass1.t1(TestClass1.java:11)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- t1 -->
        <test-method status="FAIL" signature="t2()[pri:0, instance:com.javacodegeeks.testng.reports.TestClass1@31b7dea0]" name="t2" duration-ms="1" started-at="2015-03-10T11:53:10Z" finished-at="2015-03-10T11:53:10Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at com.javacodegeeks.testng.reports.TestClass1.t2(TestClass1.java:16)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- t2 -->
        <test-method status="PASS" signature="t3()[pri:0, instance:com.javacodegeeks.testng.reports.TestClass1@31b7dea0]" name="t3" duration-ms="0" started-at="2015-03-10T11:53:10Z" finished-at="2015-03-10T11:53:10Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- t3 -->
        <test-method status="PASS" signature="t4()[pri:0, instance:com.javacodegeeks.testng.reports.TestClass1@31b7dea0]" name="t4" duration-ms="1" started-at="2015-03-10T11:53:10Z" finished-at="2015-03-10T11:53:10Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- t4 -->
        <test-method status="PASS" signature="t5(java.lang.String)[pri:0, instance:com.javacodegeeks.testng.reports.TestClass1@31b7dea0]" name="t5" duration-ms="0" started-at="2015-03-10T11:53:10Z" data-provider="dp" finished-at="2015-03-10T11:53:10Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[one]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- t5 -->
        <test-method status="PASS" signature="t5(java.lang.String)[pri:0, instance:com.javacodegeeks.testng.reports.TestClass1@31b7dea0]" name="t5" duration-ms="0" started-at="2015-03-10T11:53:10Z" data-provider="dp" finished-at="2015-03-10T11:53:10Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[two]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- t5 -->
      </class> <!-- com.javacodegeeks.testng.reports.TestClass1 -->
      <class name="com.javacodegeeks.testng.reports.TestClass">
        <test-method status="PASS" signature="a1()[pri:0, instance:com.javacodegeeks.testng.reports.TestClass@6956de9]" name="a1" duration-ms="0" started-at="2015-03-10T11:53:10Z" finished-at="2015-03-10T11:53:10Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- a1 -->
        <test-method status="FAIL" signature="a2(java.lang.String)[pri:0, instance:com.javacodegeeks.testng.reports.TestClass@6956de9]" name="a2" duration-ms="0" started-at="2015-03-10T11:53:10Z" finished-at="2015-03-10T11:53:10Z">
          <exception class="org.testng.TestNGException">
            <message>
              <![CDATA[
Parameter 'param' is required by @Test on method a2 but has not been marked @Optional or defined
in C:\javacodegeeks_ws\testngReports\src\test\resources\main-suite.xml]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.TestNGException: 
Parameter 'param' is required by @Test on method a2 but has not been marked @Optional or defined
in C:\javacodegeeks_ws\testngReports\src\test\resources\main-suite.xml
	at org.testng.internal.Parameters.createParameters(Parameters.java:155)
	at org.testng.internal.Parameters.createParameters(Parameters.java:358)
	at org.testng.internal.Parameters.handleParameters(Parameters.java:450)
	at org.testng.internal.Invoker.handleParameters(Invoker.java:1383)
	at org.testng.internal.Invoker.createParameters(Invoker.java:1075)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1180)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.TestNGException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- a2 -->
      </class> <!-- com.javacodegeeks.testng.reports.TestClass -->
    </test> <!-- main-suite-test1 -->
  </suite> <!-- main-suite -->
  <suite name="suite2" duration-ms="1" started-at="2015-03-10T06:23:10Z" finished-at="2015-03-10T06:23:10Z">
    <groups>
    </groups>
    <test name="suite2-test1" duration-ms="1" started-at="2015-03-10T06:23:10Z" finished-at="2015-03-10T06:23:10Z">
      <class name="com.javacodegeeks.testng.reports.TestClass4">
        <test-method status="PASS" signature="e1()[pri:0, instance:com.javacodegeeks.testng.reports.TestClass4@256216b3]" name="e1" duration-ms="0" started-at="2015-03-10T11:53:10Z" finished-at="2015-03-10T11:53:10Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- e1 -->
        <test-method status="PASS" signature="e2()[pri:0, instance:com.javacodegeeks.testng.reports.TestClass4@256216b3]" name="e2" duration-ms="0" started-at="2015-03-10T11:53:10Z" finished-at="2015-03-10T11:53:10Z">
          <reporter-output>
              <![CDATA[Method name is e2]]>
          </reporter-output>
        </test-method> <!-- e2 -->
      </class> <!-- com.javacodegeeks.testng.reports.TestClass4 -->
    </test> <!-- suite2-test1 -->
  </suite> <!-- suite2 -->
  <suite name="suite1" duration-ms="41" started-at="2015-03-10T06:23:10Z" finished-at="2015-03-10T06:23:10Z">
    <groups>
      <group name="myGroup">
        <method signature="TestClass1.t1()[pri:0, instance:com.javacodegeeks.testng.reports.TestClass1@5474c6c]" name="t1" class="com.javacodegeeks.testng.reports.TestClass1"/>
        <method signature="TestClass1.t2()[pri:0, instance:com.javacodegeeks.testng.reports.TestClass1@5474c6c]" name="t2" class="com.javacodegeeks.testng.reports.TestClass1"/>
        <method signature="TestClass1.t3()[pri:0, instance:com.javacodegeeks.testng.reports.TestClass1@5474c6c]" name="t3" class="com.javacodegeeks.testng.reports.TestClass1"/>
        <method signature="TestClass3.d1()[pri:0, instance:com.javacodegeeks.testng.reports.TestClass3@6ad5c04e]" name="d1" class="com.javacodegeeks.testng.reports.TestClass3"/>
      </group> <!-- myGroup -->
    </groups>
    <test name="suite1-test1" duration-ms="20" started-at="2015-03-10T06:23:10Z" finished-at="2015-03-10T06:23:10Z">
      <class name="com.javacodegeeks.testng.reports.TestClass1">
        <test-method status="FAIL" signature="t1()[pri:0, instance:com.javacodegeeks.testng.reports.TestClass1@5474c6c]" name="t1" duration-ms="0" started-at="2015-03-10T11:53:10Z" finished-at="2015-03-10T11:53:10Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at com.javacodegeeks.testng.reports.TestClass1.t1(TestClass1.java:11)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1220)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- t1 -->
        <test-method status="PASS" signature="t5(java.lang.String)[pri:0, instance:com.javacodegeeks.testng.reports.TestClass1@5474c6c]" name="t5" duration-ms="0" started-at="2015-03-10T11:53:10Z" data-provider="dp" finished-at="2015-03-10T11:53:10Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[one]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- t5 -->
        <test-method status="PASS" signature="t5(java.lang.String)[pri:0, instance:com.javacodegeeks.testng.reports.TestClass1@5474c6c]" name="t5" duration-ms="0" started-at="2015-03-10T11:53:10Z" data-provider="dp" finished-at="2015-03-10T11:53:10Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[two]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- t5 -->
        <test-method status="PASS" signature="t3()[pri:0, instance:com.javacodegeeks.testng.reports.TestClass1@5474c6c]" name="t3" duration-ms="0" started-at="2015-03-10T11:53:10Z" finished-at="2015-03-10T11:53:10Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- t3 -->
        <test-method status="PASS" signature="t4()[pri:0, instance:com.javacodegeeks.testng.reports.TestClass1@5474c6c]" name="t4" duration-ms="0" started-at="2015-03-10T11:53:10Z" finished-at="2015-03-10T11:53:10Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- t4 -->
        <test-method status="FAIL" signature="t2()[pri:0, instance:com.javacodegeeks.testng.reports.TestClass1@5474c6c]" name="t2" duration-ms="0" started-at="2015-03-10T11:53:10Z" finished-at="2015-03-10T11:53:10Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at com.javacodegeeks.testng.reports.TestClass1.t2(TestClass1.java:16)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1220)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- t2 -->
      </class> <!-- com.javacodegeeks.testng.reports.TestClass1 -->
      <class name="com.javacodegeeks.testng.reports.TestClass2">
        <test-method status="PASS" signature="c3()[pri:0, instance:com.javacodegeeks.testng.reports.TestClass2@2fc14f68]" name="c3" duration-ms="0" started-at="2015-03-10T11:53:10Z" finished-at="2015-03-10T11:53:10Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- c3 -->
        <test-method status="PASS" signature="c2()[pri:0, instance:com.javacodegeeks.testng.reports.TestClass2@2fc14f68]" name="c2" duration-ms="0" started-at="2015-03-10T11:53:10Z" finished-at="2015-03-10T11:53:10Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- c2 -->
        <test-method status="FAIL" signature="c4()[pri:0, instance:com.javacodegeeks.testng.reports.TestClass2@2fc14f68]" name="c4" duration-ms="0" started-at="2015-03-10T11:53:10Z" finished-at="2015-03-10T11:53:10Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at com.javacodegeeks.testng.reports.TestClass2.c4(TestClass2.java:22)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1220)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- c4 -->
        <test-method status="PASS" signature="c1()[pri:0, instance:com.javacodegeeks.testng.reports.TestClass2@2fc14f68]" name="c1" duration-ms="0" started-at="2015-03-10T11:53:10Z" finished-at="2015-03-10T11:53:10Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- c1 -->
      </class> <!-- com.javacodegeeks.testng.reports.TestClass2 -->
    </test> <!-- suite1-test1 -->
    <test name="suite1-test2" duration-ms="0" started-at="2015-03-10T06:23:10Z" finished-at="2015-03-10T06:23:10Z">
      <class name="com.javacodegeeks.testng.reports.TestClass3">
        <test-method status="PASS" signature="d1()[pri:0, instance:com.javacodegeeks.testng.reports.TestClass3@6ad5c04e]" name="d1" duration-ms="0" started-at="2015-03-10T11:53:10Z" finished-at="2015-03-10T11:53:10Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- d1 -->
        <test-method status="PASS" signature="d2()[pri:0, instance:com.javacodegeeks.testng.reports.TestClass3@6ad5c04e]" name="d2" duration-ms="0" started-at="2015-03-10T11:53:10Z" finished-at="2015-03-10T11:53:10Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- d2 -->
      </class> <!-- com.javacodegeeks.testng.reports.TestClass3 -->
      <class name="com.javacodegeeks.testng.reports.FactoryInstantiatedTestClass">
        <test-method status="PASS" signature="f()[pri:0, instance:com.javacodegeeks.testng.reports.FactoryInstantiatedTestClass@6833ce2c]" test-instance-name="FactoryInstantiatedTestClass-TestNG" name="f" duration-ms="0" started-at="2015-03-10T11:53:10Z" finished-at="2015-03-10T11:53:10Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- f -->
        <test-method status="FAIL" signature="f()[pri:0, instance:com.javacodegeeks.testng.reports.FactoryInstantiatedTestClass@725bef66]" test-instance-name="FactoryInstantiatedTestClass-Reports" name="f" duration-ms="0" started-at="2015-03-10T11:53:10Z" finished-at="2015-03-10T11:53:10Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at com.javacodegeeks.testng.reports.FactoryInstantiatedTestClass.f(FactoryInstantiatedTestClass.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1220)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- f -->
      </class> <!-- com.javacodegeeks.testng.reports.FactoryInstantiatedTestClass -->
    </test> <!-- suite1-test2 -->
  </suite> <!-- suite1 -->
</testng-results>
